# -*- coding: utf-8 -*-
"""audio_currency.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FEljjxSC5K1t0hyW4kUHgUr35Shi_yW5
"""

!pip install gtts

import cv2
import numpy as np
import tensorflow as tf
from google.colab import drive
from gtts import gTTS
import IPython.display as ipd
import os

drive.mount('/content/drive')

model_path = "/content/drive/MyDrive/currency_model_2.h5"

def preprocess_image(image_path):
    image = cv2.imread(image_path)
    image = cv2.resize(image, (224, 224))
    image = image / 255.0
    image = np.expand_dims(image, axis=0)
    return image

def predict_currency(image_path):
    image = preprocess_image(image_path)
    predictions = model.predict(image)
    class_idx = np.argmax(predictions)
    currency_labels = {
        0: "10 Rupees",
        1: "20 Rupees",
        2: "50 Rupees",
        3: "100 Rupees",
        4: "200 Rupees",
        5: "500 Rupees",
        6: "2000 Rupees"
    }
    currency_detected = currency_labels.get(class_idx, "Unknown Currency")
    text = f"The detected currency is {currency_detected}"
    tts = gTTS(text=text, lang='en')
    tts.save("currency_audio.mp3")
    ipd.display(ipd.Audio("currency_audio.mp3", autoplay=True))
    print(f"Detected Currency: {currency_detected}")
    return currency_detected

